# Generated by Django 4.0.4 on 2022-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
