# Generated by Django 4.0.4 on 2022-05-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safemanager', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Maried', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='Single', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='office_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport',
            field=models.ImageField(null=True, upload_to='custom'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
