# Generated by Django 4.0.4 on 2022-05-16 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safemanager', '0006_customer_customer_id_customer_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer_group',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
