# Generated by Django 4.0.4 on 2022-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safemanager', '0007_customer_group_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_group',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
